### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by lfb6054** [vipulSharma18/Automatic-Emotion-Recognition-on-DEAP-Dataset#1]
Can you share your: 
labels= pd.read_ excel("/content/drive/MyDrive/major project/metadata/ Labels.xls ")
These ". XLS" files? I can't load them. Can you help me? Thank you very much.

**Comment by vipulSharma18** [comment]
https://www.eecs.qmul.ac.uk/mmv/datasets/deap/

The dataset is not open to the public and its access will have to be requested from this website. From there on it's simple.
